### ISSUE TITLE
Problema en Ubuntu 20.04

### ISSUE THREAD

**Issue by amartinr1977** [migasfree/migasfree-sdk#2]
Buenos días,

Comentaros que en Ubuntu 20.04 da problemas al instalar migasfree-sdk, ya que depende de python-requests y este paquete como tal ya no está disponible. En 20.04 esta python3-request, que no se si sería válido ... de ser así podría construir el paquete modificando la dependencia.  Ya nos diréis. Saludos!!

-- Arturo Marin (Vitalinux)

**Comment by agacias** [comment]
¿Has bajado el paquete de http://www.migasfree.org/pub/ubuntu.20/REPOSITORIES/dists/migasfree/PKGS/ ? 

Si has puesto el de una versión de Ubuntu anterior (con python2) es posible que ese sea el problema. Ya nos dirás.

**Comment by amartinr1977** [comment]
Ahora sin problemas!! Mil gracias Alberto!! Había bajado el código de Gitlab, la última versión disponible, y había construido el paquete.  No se que debía hacer mal ...
La URL que me has indicado, http://www.migasfree.org/pub/ubuntu.20/REPOSITORIES/dists/migasfree/PKGS/, no la sabíamos, o no la recordabamos ... Desde http://www.migasfree.org/ no ví el enlace de como llegar a vuestros repos públicos de distribución de paquetes.
Gracias nuevamente!!!
